[package]
name = "vivespire"
version = "0.1.0"
authors = ["Ryan Sivek <developer@ryansivek.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "3.7"
rand = "0.8"
serde_json = "1.0"
strum = "0.26.1"
strum_macros = "0.26.1"
either = "1.8"
simple-si-units = "1.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.petgraph]
version = "0.6"
features = ["serde-1"]

[dependencies.uuid]
version = "0.8"
features = ["serde", "v4"]

[dev-dependencies]
simple_logger = "1.11.0"
