[package]
name = "desbios"
version = "0.1.0"
authors = ["Ryan Sivek <rysivek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
approx = "0.3.2"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
log = "0.4"
ordered-float = "2.0"
rand = "0.7.3"
serde_json = "1.0"
petgraph = "0.5.1"

[dependencies.uom]
version = "0.31.0"
default-features = false
features = ["autoconvert", "rational", "f64", "si", "std", "try-from", "use_serde"]

[dependencies.uuid]
version = "0.8"
features = ["serde", "v4"]

[dev-dependencies]
simple_logger = "1.11.0"