[package]
name = "desbios"
version = "0.1.0"
authors = ["Ryan Sivek <rysivek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4"
ordered-float = "2.0"
uom = { version = "0.29.0", default-features = false, features = ["autoconvert", "rational", "f64", "si", "std", "try-from", "use_serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
