[package]
name = "desbios"
version = "0.1.0"
authors = ["Ryan Sivek <rysivek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }