---
path: mortalsim-human/src/human_anatomy.rs
regions:
  - Cranial
  - Nasal
  - LeftFacial
  - RightFacial
  - Cervical
  - LeftScapular
  - RightScapular
  - Dorsal
  - Lumbar
  - Sacral
  - Thoracic
  - LeftMammary
  - RightMammary
  - LeftUpperAbdominal
  - LeftLowerAbdominal
  - RightUpperAbdominal
  - RightLowerAbdominal
  - Umbilical
  - LeftCoxal
  - RightCoxal
  - Pubic
  - LeftAxillary
  - LeftBrachial
  - LeftAntecubital
  - LeftOlecranal
  - LeftAntebrachial
  - LeftCarpal
  - LeftPalmar
  - LeftManus
  - LeftUpperPhalangeal
  - RightAxillary
  - RightBrachial
  - RightAntecubital
  - RightOlecranal
  - RightAntebrachial
  - RightCarpal
  - RightPalmar
  - RightManus
  - RightUpperPhalangeal
  - LeftInguinal
  - LeftGluteal
  - LeftFemoral
  - LeftPatellar
  - LeftPopliteal
  - LeftCrural
  - LeftSural
  - LeftFibular
  - LeftCalcaneal
  - LeftTarsal
  - LeftPedal
  - LeftLowerPhalangeal
  - LeftPlantar
  - RightInguinal
  - RightGluteal
  - RightFemoral
  - RightPatellar
  - RightPopliteal
  - RightCrural
  - RightSural
  - RightFibular
  - RightCalcaneal
  - RightTarsal
  - RightPedal
  - RightLowerPhalangeal
  - RightPlantar
