use crate::blood::BloodVessel;
use crate::blood::circulation::CirculationDef;

pub type HumanCirculationDef = CirculationDef<HumanBloodVessel>;

pub const HUMAN_CIRCULATION_FILEPATH: &str = "config/circulation/human_circulation.json";

#[derive(Debug, Display, Hash, Clone, Copy, PartialEq, Eq, EnumString, EnumVariantNames)]
pub enum HumanBloodVessel {
    Aorta,
    RightBraciocephalicArtery,
    RightSubclavianArtery,
    RightAxillaryArtery,
    RightBrachialArtery,
    RightUlnarArtery,
    RightRadialArtery,
    RightCommonCarotidArtery,
    RightCarotidSinusArtery,
    RightInternalCarotidArtery,
    RightExternalCarotidArtery,
    LeftSubclavianArtery,
    LeftAxillaryArtery,
    LeftBrachialArtery,
    LeftUlnarArtery,
    LeftRadialArtery,
    LeftCommonCarotidArtery,
    LeftCarotidSinusArtery,
    LeftInternalCarotidArtery,
    LeftExternalCarotidArtery,
    ThoracicAorta,
    AbdominalAorta,
    CeliacArtery,
    CommonHepaticArtery,
    RightGastricArtery,
    SplenicArtery,
    LeftGastricArtery,
    SuperiorMesentericArtery,
    InferiorMesentericArtery,
    RightRenalArtery,
    LeftRenalArtery,
    RightCommonIliacArtery,
    RightInternalIliacArtery,
    RightExternalIliacArtery,
    RightCommonFemoralArtery,
    RightDeepFemoralArtery,
    RightSuperficialFemoralArtery,
    RightPoplitealArtery,
    RightAnteriorTibialArtery,
    RightPosteriorTibialArtery,
    RightFibularArtery,
    LeftCommonIliacArtery,
    LeftInternalIliacArtery,
    LeftExternalIliacArtery,
    LeftCommonFemoralArtery,
    LeftDeepFemoralArtery,
    LeftSuperficialFemoralArtery,
    LeftPoplitealArtery,
    LeftAnteriorTibialArtery,
    LeftPosteriorTibialArtery,
    LeftFibularArtery,
    VenaCava,
    SuperiorVenaCava,
    RightBrachiocephalicVein,
    RightSubclavianVein,
    RightAxillaryVein,
    RightBasilicVein,
    RightCephalicVein,
    RightInternalJugularVein,
    LeftBrachiocephalicVein,
    LeftSubclavianVein,
    LeftAxillaryVein,
    LeftBasilicVein,
    LeftCephalicVein,
    LeftInternalJugularVein,
    InferiorVenaCava,
    HepaticVein,
    SplenicVein,
    SuperiorMesentericVein,
    InferiorMesentericVein,
    LeftGastricVein,
    RightGastricVein,
    LeftRenalVein,
    RightRenalVein,
    RightCommonIliacVein,
    RightInternalIliacVein,
    RightExternalIliacVein,
    RightDeepFemoralVein,
    RightGreatSaphenousVein,
    RightFemoralVein,
    RightPoplitealVein,
    RightSmallSaphenousVein,
    RightAnteriorTibialVein,
    RightPosteriorTibialVein,
    LeftCommonIliacVein,
    LeftInternalIliacVein,
    LeftExternalIliacVein,
    LeftDeepFemoralVein,
    LeftGreatSaphenousVein,
    LeftFemoralVein,
    LeftPoplitealVein,
    LeftSmallSaphenousVein,
    LeftAnteriorTibialVein,
    LeftPosteriorTibialVein,
}

impl BloodVessel for HumanBloodVessel {}
