
/*
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * SOURCE: config/test/anatomy.yaml
 */

use crate::sim::organism::AnatomicalRegion;

#[derive(Debug, Display, Hash, Clone, Copy, PartialEq, Eq, EnumString, IntoStaticStr)]
pub enum TestAnatomicalRegion {
    Head,
    Torso,
    LeftArm,
    RightArm,
    LeftLeg,
    RightLeg
}

impl AnatomicalRegion for TestAnatomicalRegion {}
