const yaml = require('yaml');
const fs = require('fs');
const path = require('path');

fs.readdirSync(__dirname)
    .filter(f => f != 'node_modules')
    .filter(f => fs.statSync(path.join(__dirname, f)).isDirectory())
    .forEach(dir => {
        console.log(dir);
        let configFile = fs.readFileSync(path.join(__dirname, dir, 'anatomy.yaml'), 'utf8');
        let config = yaml.parse(configFile);
        writeAnatomyFile(dir, config);
    });

function writeAnatomyFile(namespace, config) {
    let namespaceCapitalized = namespace.charAt(0).toUpperCase() + namespace.slice(1);

    let sysPath = config.path.replace(/\//g, path.sep);

    fs.writeFileSync(`../${sysPath}`, `
/*
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * SOURCE: config/${namespace}/anatomy.yaml
 */

#[derive(Debug, Display, Hash, Clone, Copy, PartialEq, Eq, EnumString, IntoStaticStr)]
pub enum ${namespaceCapitalized}AnatomicalRegion {
    ${config.regions.join(',\n    ')}
}
`)
}
