ADP:
  name: Adenosine Diphosphate
  charge: 0
  molar_mass: 427.201
  density: 2.49
AMP:
  name: Adenosine Monophosphate
  charge: 0
  molar_mass: 347.2212
  density: 1.04
ATP:
  name: Adenosine Triphosphate
  charge: 0
  molar_mass: 507.18
  density: 1.04
Ca:
  name: Calcium
  charge: 2
  molar_mass: 40.078
  density: 1.55
CO2:
  name: Carbon Dioxide
  charge: 0
  molar_mass: 44.01
  density: 0.001977
Cl:
  name: Chloride
  charge: -1
  molar_mass: 35.453
  density: 0.0032
GLC:
  name: Alpha D Glucose
  charge: 0
  molar_mass: 180.156
  density: 1.54
GLCL:
  name: L-Glucose
  charge: 0
  molar_mass: 180.156
  density: 1.54
FRC:
  name: Fructose
  charge: 0
  molar_mass: 180.156
  density: 1.694
H:
  name: Hydrogen
  charge: 1
  molar_mass: 1.00794
  density: 0.00008988
H2O:
  name: Water
  charge: 0
  molar_mass: 18.0153
  density: 1
K:
  name: Potassium
  charge: 1
  molar_mass: 39.0983
  density: 0.862
LAC:
  name: Lactate
  charge: 0
  molar_mass: 89.07
  density: 1.21
LDH:
  name: Lactate Dehydrogenase
  charge: 0
  molar_mass: 144000
  density: 1.43
N2:
  name: Dinitrogen
  charge: 0
  molar_mass: 28.0134
  density: 0.001251
NAD:
  name: Nicotinamide Adenine Dinucleotide
  charge: 1
  molar_mass: 663.43
  density: 1.578
NADH:
  name: Reduced NAD
  charge: 0
  molar_mass: 665.125
  density: 1.578
Na:
  name: Sodium
  charge: 1
  molar_mass: 22.989769
  density: 0.97
NaCl:
  name: Salt
  charge: 0
  molar_mass: 58.44
  density: 2.16
O2:
  name: Dioxygen
  charge: 0
  molar_mass: 31.9988
  density: 0.001429
PFK:
  name: Phosphofructokinase
  charge: 0
  molar_mass: 85000
  density: 1.5625
PGK:
  name: Phosphoglycerate Kinase
  charge: 0
  molar_mass: 45000
  density: 1.642
PYR:
  name: Pyruvate
  charge: 0
  molar_mass: 88.06
  density: 1.25
MSG:
  name: Monosodium Glutamate
  charge: 0
  molar_mass: 88.06
  density: 1.52
NH3:
  name: Ammonia
  charge: 0
  molar_mass: 17.031
  density: 0.73
NaClO:
  name: Bleach
  charge: 0
  molar_mass: 74.44
  density: 1.11

# Amino Acids
ALA:
  name: Alanine
  charge: 0
  molar_mass: 89.1
  density: 1.42
ARG:
  name: Arginine
  charge: 1
  molar_mass: 174.2
  density: 1.48
ASN:
  name: Asparagine
  charge: 0
  molar_mass: 132.1
  density: 1.53
ASP:
  name: Aspartic Acid
  charge: -1
  molar_mass: 133.1
  density: 1.66
CYS:
  name: Cysteine
  charge: 0
  molar_mass: 121.6
  density: 1.92
GLN:
  name: Glutamine
  charge: 0
  molar_mass: 146.1
  density: 1.36
GLU:
  name: Glutamic Acid
  charge: -1
  molar_mass: 147.1
  density: 1.54
GLY:
  name: Glycine
  charge: 0
  molar_mass: 75.1
  density: 1.6
HIS:
  name: Histidine
  charge: 1
  molar_mass: 155.2
  density: 1.49
ILE:
  name: Isoleucine
  charge: 0
  molar_mass: 131.2
  density: 1.34
LEU:
  name: Leucine
  charge: 0
  molar_mass: 131.2
  density: 1.34
LYS:
  name: Lysine
  charge: 1
  molar_mass: 146.2
  density: 1.36
MET:
  name: Methionine
  charge: 0
  molar_mass: 149.2
  density: 1.34
PHE:
  name: Phenylalanine
  charge: 0
  molar_mass: 165.2
  density: 1.08
PRO:
  name: Proline
  charge: 0
  molar_mass: 115.1
  density: 1.36
SER:
  name: Serine
  charge: 0
  molar_mass: 105.1
  density: 1.48
THR:
  name: Threonine
  charge: 0
  molar_mass: 119.2
  density: 1.31
TRP:
  name: Tryptophan
  charge: 0
  molar_mass: 204.2
  density: 1.2
TYR:
  name: Tyrosine
  charge: 0
  molar_mass: 181.2
  density: 1.18
VAL:
  name: Valine
  charge: 0
  molar_mass: 117.5
  density: 1.23

# Vitamins
Retinol:
  name: Vitamin A
  charge: 0
  molar_mass: 286.459
  density: 0.944
Retinal:
  name: Vitamin A Aldehyde
  charge: 0
  molar_mass: 284.443
  density: 0.97
RetinoicAcid:
  name: Vitamin A Acid
  charge: 0
  molar_mass: 300.43512
  density: 1.06
Thiamine:
  name: Vitamin B1
  charge: 1
  molar_mass: 265.36
  density: 1.24
Riboflavin:
  name: Vitamin B2
  charge: 0
  molar_mass: 376.369
  density: 1.454
Niacin:
  name: Vitamin B3
  charge: 0
  molar_mass: 123.111
  density: 1.473
PantothenicAcid:
  name: Vitamin B5
  charge: 0
  molar_mass: 219.237
  density: 1.213
Pyridoxine:
  name: Vitamin B6
  charge: 0
  molar_mass: 169.180
  density: 1.626
Biotin:
  name: Vitamin B7
  charge: 0
  molar_mass: 244.31
  density: 1.213
Folate:
  name: Vitamin B9
  charge: 0
  molar_mass: 441.404
  density: 1.77
HdxCbl:
  name: Vitamin B12a
  charge: 0
  molar_mass: 1346.377
  density: 1.9
AdoCbl:
  name: Coenzyme B12
  charge: 0
  molar_mass: 1579.608
  density: 1.12
MeCbl:
  name: Methylcobalamin B12
  charge: 0
  molar_mass: 1344.405
  density: 1.37
CynCbl:
  name: Cyanocobalamin B12
  charge: 0
  molar_mass: 1355.388
  density: 1.53
AscorbicAcid:
  name: Vitamin C
  charge: 0
  molar_mass: 176.124
  density: 1.65
Ergocalciferol:
  name: Vitamin D2
  charge: 0
  molar_mass: 396.659
  density: 0.94
Cholecalciferol:
  name: Vitamin D3
  charge: 0
  molar_mass: 384.648
  density: 0.96
AlphaTocopherol:
  name: Vitamin E
  charge: 0
  molar_mass: 430.71
  density: 0.95
BetaTocopherol:
  name: Vitamin E
  charge: 0
  molar_mass: 416.68
  density: 0.95
DeltaTocopherol:
  name: Vitamin E
  charge: 0
  molar_mass: 402.65
  density: 0.96
GammaTocopherol:
  name: Vitamin E
  charge: 0
  molar_mass: 416.68
  density: 0.95
AlphaTocotrienol:
  name: Vitamin E
  charge: 0
  molar_mass: 424.7
  density: 0.88
BetaTocotrienol:
  name: Vitamin E
  charge: 0
  molar_mass: 410.6
  density: 0.89
DeltaTocotrienol:
  name: Vitamin E
  charge: 0
  molar_mass: 396.6
  density: 0.91
GammaTocotrienol:
  name: Vitamin E
  charge: 0
  molar_mass: 410.6
  density: 0.89
Phytomenadione:
  name: Vitamin K1
  charge: 0
  molar_mass: 450.707
  density: 0.989
MK4:
  name: Vitamin K2-4
  charge: 0
  molar_mass: 444.659
  density: 1.1
Menadione:
  name: Vitamin K3
  charge: 0
  molar_mass: 172.183
  density: 1.28

# Polysaccharides
Amylose:
  name: Starch
  charge: 0
  molar_mass: 100000
  density: 1.5
Amylopectin:
  name: Starch
  charge: 0
  molar_mass: 1500000
  density: 1.6
Cellulose:
  name: Cellulose
  charge: 0
  molar_mass: 162000
  density: 1.5
Glycogen:
  name: Glycogen
  charge: 0
  molar_mass: 5404680
  density: 1.6
