const yaml = require('yaml');
const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, '..', 'config');

fs.readdirSync(configPath)
    .filter(f => fs.statSync(path.join(configPath, f)).isDirectory())
    .filter(f => f === 'test')
    .forEach(dir => {
        console.log(dir);
        let configFile = fs.readFileSync(path.join(configPath, dir, 'anatomy.yaml'), 'utf8');
        let config = yaml.parse(configFile);
        writeAnatomyFile(dir, config);
    });

function writeAnatomyFile(namespace, config) {
    let namespaceCapitalized = namespace.charAt(0).toUpperCase() + namespace.slice(1);

    let sysPath = config.path.replace(/\//g, path.sep);

    fs.writeFileSync(path.join(configPath, '..', sysPath), `
/*
 * THIS FILE IS AUTOMATICALLY GENERATED.
 * SOURCE: config/${namespace}/anatomy.yaml
 */

use crate::sim::organism::AnatomicalRegion;

#[derive(Debug, Display, Hash, Clone, Copy, PartialEq, Eq, EnumString, IntoStaticStr)]
pub enum ${namespaceCapitalized}AnatomicalRegion {
    ${config.regions.join(',\n    ')}
}

impl AnatomicalRegion for ${namespaceCapitalized}AnatomicalRegion {}
`)
}
